"""Small NDJSON fixture mirroring the real trufflehog output shape."""

TRUFFLEHOG_NDJSON = """\
{"SourceMetadata":{"Data":{"Git":{"commit":"d049d566b6fef7d192dcc2e8a37a05fe891e726d","file":"simple.py","email":"Diogo Lemos <diogo.lemos@olx.com>","repository":"https://github.com/lemosdsec/wmata-trains.git","timestamp":"2024-11-05 11:12:45 +0000","line":11}}},"SourceID":1,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":904,"DetectorName":"CustomRegex","DecoderName":"PLAIN","Verified":false,"Raw":"password=DB_CONFIG[\\"password\\"]","RawV2":"","Redacted":"","ExtraData":{},"StructuredData":null}
{"SourceMetadata":{"Data":{"Git":{"commit":"d049d566b6fef7d192dcc2e8a37a05fe891e726d","file":"trains.py","email":"Diogo Lemos <diogo.lemos@olx.com>","repository":"https://github.com/lemosdsec/wmata-trains.git","timestamp":"2024-11-05 11:12:45 +0000","line":34}}},"SourceID":1,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":904,"DetectorName":"CustomRegex","DecoderName":"PLAIN","Verified":false,"Raw":"\\"Authorization\\": f\\"Bearer {MOBILE_AUTH['app_secret']}\\"","RawV2":"","Redacted":"","ExtraData":{},"StructuredData":null}
{"SourceMetadata":{"Data":{"Git":{"commit":"ab402e7f3a7fa9da69f2fb7367dbb9274083ad0d","file":"secrets.json","email":"Diogo Lemos <diogo.lemos@olx.com>","repository":"https://github.com/lemosdsec/wmata-trains.git","timestamp":"2024-11-05 11:10:08 +0000","line":11}}},"SourceID":1,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":904,"DetectorName":"CustomRegex","DecoderName":"PLAIN","Verified":true,"Raw":"Pr0d-P@ssw0rd-2024!","RawV2":"","Redacted":"","ExtraData":{},"StructuredData":null}
{"SourceMetadata":{"Data":{"Git":{"commit":"bf611138159dcc3990db17a25071442296aae4df","file":"config.py","email":"Diogo Lemos <diogo.lemos@olx.com>","repository":"https://github.com/lemosdsec/wmata-trains.git","timestamp":"2024-11-05 10:52:35 +0000","line":3}}},"SourceID":1,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":904,"DetectorName":"CustomRegex","DecoderName":"PLAIN","Verified":false,"Raw":"CLIENT_SECRET = \\"abcdef12345hijklmnop67890qrstuv\\"","RawV2":"","Redacted":"","ExtraData":{},"StructuredData":null}
{"SourceMetadata":{"Data":{"Git":{"commit":"bf611138159dcc3990db17a25071442296aae4df","file":"config.py","email":"Diogo Lemos <diogo.lemos@olx.com>","repository":"https://github.com/lemosdsec/wmata-trains.git","timestamp":"2024-11-05 10:52:35 +0000","line":14}}},"SourceID":1,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":904,"DetectorName":"CustomRegex","DecoderName":"PLAIN","Verified":false,"Raw":"\\"password\\": \\"SuperSecretPass123!\\"","RawV2":"","Redacted":"","ExtraData":{},"StructuredData":null}
"""


TRUFFLEHOG_LINES = [line for line in TRUFFLEHOG_NDJSON.splitlines() if line.strip()]
