# Generated by Django 5.2.8 on 2026-04-28 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_finding_related_to'),
        ('vulns', '0002_alter_finding_related_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(help_text='Raw secret value as reported by the scanner')),
                (
                    'secret_hash',
                    models.CharField(
                        db_index=True, help_text='SHA256 of `secret` for safe lookups and dedup', max_length=64
                    ),
                ),
                (
                    'source',
                    models.CharField(help_text="Scanner name, e.g. 'trufflehog', 'git-history-scan'", max_length=64),
                ),
                (
                    'kind',
                    models.CharField(
                        blank=True,
                        help_text="Detector / file type, e.g. 'CustomRegex', 'AWS', 'SensitiveFile(.env)'",
                        max_length=128,
                    ),
                ),
                ('verified', models.BooleanField(db_index=True, default=False)),
                (
                    'verification_error',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Optional message explaining why trufflehog could not verify this finding',
                    ),
                ),
                (
                    'extra_data',
                    models.JSONField(
                        blank=True,
                        help_text='Detector-specific extra data (trufflehog `ExtraData` / `StructuredData`)',
                        null=True,
                    ),
                ),
                ('environment', models.CharField(blank=True, default='Unknown', max_length=64)),
                (
                    'state',
                    models.IntegerField(
                        choices=[(1, 'New'), (2, 'Open'), (4, 'Fixed'), (5, 'False Positive'), (6, 'Risk Accepted')],
                        db_index=True,
                        default=1,
                    ),
                ),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'git_source',
                    models.ForeignKey(
                        blank=True,
                        help_text='Primary repository this secret was first seen in',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='secrets',
                        to='inventory.gitsource',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        help_text='Person responsible for the secret (Surface has no Team model)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='inventory.person',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Secret',
                'verbose_name_plural': 'Secrets',
                'unique_together': {('secret_hash', 'source')},
            },
        ),
        migrations.CreateModel(
            name='SecretLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('commit', models.CharField(max_length=40)),
                ('line', models.CharField(default='N/A', max_length=10)),
                ('author', models.EmailField(default='unknown@example.com', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'state',
                    models.IntegerField(
                        choices=[(1, 'New'), (2, 'Open'), (4, 'Fixed'), (5, 'False Positive'), (6, 'Risk Accepted')],
                        db_index=True,
                        default=1,
                    ),
                ),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('location_hash', models.CharField(editable=False, max_length=64, unique=True)),
                (
                    'secret',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locations',
                        to='secretsmanager.secret',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Secret Location',
                'verbose_name_plural': 'Secret Locations',
                'ordering': ['-timestamp', 'file_path'],
            },
        ),
        migrations.CreateModel(
            name='SecretFinding',
            fields=[
                (
                    'finding_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='vulns.finding',
                    ),
                ),
                (
                    'secret_location',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='finding',
                        to='secretsmanager.secretlocation',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Secret Finding',
                'verbose_name_plural': 'Secret Findings',
            },
            bases=('vulns.finding',),
        ),
    ]
